stages:      
  - test

pytest: 
  stage: test
  tags:
    - test-runner
  image: continuumio/miniconda3
  script:
    - conda env create -f environment.local.yml -n thesis
    - source activate thesis
    - pytest -v