stages:      
  - test

pytest: 
  stage: test
  tags:
    - test-runner
  before_script:
    - $env:Path += ";C:\Users\xiaox\anaconda3\Scripts;C:\Users\xiaox\anaconda3"
  script:
    - echo "Running tests in 'thesis' environment..."
    - conda run -n thesis pytest -v